# /docker-compose.yml

services:
  nextjs-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.init
    volumes:
      - .:/app

  nextjs-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./intrepion-to-do-next-js:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  nextjs-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile.publish
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
