# /docker/Dockerfile.init

# Project initialization
FROM node:22.0.0
WORKDIR /app
COPY init.sh .
RUN apt-get update && \
    apt-get install -y dos2unix && \
    dos2unix init.sh && \
    chmod +x init.sh
ENTRYPOINT ["/bin/bash", "init.sh"]
