defaults:
  run:
    working-directory: ./intrepion_to-do_web

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./intrepion_to-do_web/package-lock.json
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check linting
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: Build application
        run: npm run build --if-present

      # - name: Run unit tests
      #   run: npm run test

      - name: Run application in background
        run: npm run dev &

      # - name: Run acceptance tests
      #   run: npm run accept

      # - if: failure()
      #   name: Upload screenshots
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cypress-screenshots-${{ matrix.node-version }}
      #     path: intrepion_to-do_web/cypress/screenshots

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./

    strategy:
      matrix:
        node-version: [20]

name: Vercel Production Deployment

on:
  push:
    branches:
      - main
